### ISSUE TITLE
PHP部分处理上传成功后返回的json格式的什么样的？

### ISSUE THREAD

**Issue by dedehtml** [joker-pper/WebUploaderSupport#2]
PHP部分处理上传成功后返回的json格式的什么样的？

**Comment by joker-pper** [comment]
e.g
上传成功通过返回的attrs属性会将属性设置到对应的item中,目前默认的作为服务器文件的属性是data-server-file,删除对应资源url的属性名称是data-delete-url.
{
"attrs":{"data-server-file":true,"data-delete-url":""}
}

**Comment by joker-pper** [comment]
大致更新了一下说明,参考那个吧。
