### ISSUE TITLE
有BUG，限制了个数为6，先上传5个，然后再选择图片，又可以上传6了，可以只要不是一次性上传6个就可以无限上传

### ISSUE THREAD

**Issue by dedehtml** [joker-pper/WebUploaderSupport#3]
有BUG，限制了个数为6，先上传5个，然后再选择图片，又可以上传6了，可以只要不是一次性上传6个就可以无限上传

**Comment by joker-pper** [comment]
目前应该是通过元素属性判断文件个数的,上传成功后要作为服务端文件，不知道是否有标识为服务端文件，当前默认的上传成功返回的json应该是 {"attrs":{"data-server-file":true,"data-delete-url":""} },当然也不排除存在bug的。

**Comment by diskson** [comment]
特别感谢作者百忙之中还来处理BUG并更新了插件。但是今天更新的版本还是存在问题，限制6个，先上传5个，再添加1个不上传，然后删除它，再去选择图片，发现按钮无反应了。

**Comment by joker-pper** [comment]
默认是不能添加重复的文件的。
