### ISSUE TITLE
拖拽上传

### ISSUE THREAD

**Issue by haochanghai** [joker-pper/WebUploaderSupport#7]
拖拽上传文件夹是怎么做的？
我用WebUploader只能拖拽上传文件，文件夹不起作用！

**Comment by joker-pper** [comment]
你去找下webuploader本身是否支持这样的功能，另外这个项目本身只是集成并拥有一定业务逻辑可以进行一些简单配置项就能直接使用的，其本质还是webuploader。另外你可以尝试使用多选上传的方式嘛。

**Comment by joker-pper** [comment]
我大致试了一下，最新版谷歌浏览器支持直接拖拽文件夹，ie11不支持。

**Comment by haochanghai** [comment]
你直接用的WebUploader.js直接试的？

**Comment by haochanghai** [comment]
我不用你封装的这个js直接用WebUploader不能拖拽文件夹
你如果测试的是WebUploader，能不能测试代码发我一下。

**Comment by joker-pper** [comment]
Readme里面不是有链接嘛，我通过编辑页面测试的。另外源码有一定注释，如果要参考实现某些功能你可以大致看一下。
