### ISSUE TITLE
怎么可以限制图片大小和宽度

### ISSUE THREAD

**Issue by 393313107** [joker-pper/WebUploaderSupport#9]
怎么可以限制图片大小和宽度

**Comment by joker-pper** [comment]
重写beforeFileQueued的逻辑 采用 之前 + 自定义验证

**Comment by 393313107** [comment]
> 重写beforeFileQueued的逻辑采用之前+自定义验证

还有一些问题，比如说用多个实例的时候，当图片个数换行后，上传按钮隐藏的点击区域就移位了等等，你的demo里就有这个问题，请问后续有解决吗。能添加您一个联系方式吗，想询问一些有关框架的问题

**Comment by joker-pper** [comment]
换行之后按钮的样式有乱掉么 你可以通过示例页面测试下 重写方法的可以参考提供的示例

**Comment by 393313107** [comment]
> 换行之后按钮的样式有乱掉么你可以通过示例页面测试下重写方法的可以参考提供的示例

是的，换行之后样式没有乱，但是隐藏的点击域已经移位了，不在按钮的那个位置了，就是你的示例文件里也有这个问题

**Comment by joker-pper** [comment]
隐藏域的结构可能并不标准 上传按钮不能触发上传时才有问题

**Comment by 393313107** [comment]
> 隐藏域的结构可能并不标准上传按钮不能触发上传时才有问题

就是一个意思，比如多实例，你第二个实例图片换行后，你第一个个实例的上传按钮已经无效了，我看了下结构，隐藏域已经被高度撑的移位了，您可以试下您项目的示例demo

**Comment by joker-pper** [comment]
https://joker-pper.github.io/WebUploaderSupport/webuploader.support/edit.html 
这个页面谷歌测试没有问题 可能是浏览器或其他原因导致的

**Comment by 393313107** [comment]
> https://joker-pper.github.io/WebUploaderSupport/webuploader.support/edit.html
> 这个页面谷歌测试没有问题可能是浏览器或其他原因导致的

刚试完你这个也是有问题哦，bug操作：你在第三个实例添加6张图片（目的是为了换行），然后你再点击你第一个实例的选择图片按钮，已经无法触发了，你看结构可以看到隐藏域已经移位了

**Comment by joker-pper** [comment]
确实存在这样的问题 应该是框架自身的bug 
目前通过实例化后调用 refresh 选择文件的生成元素结构看起来是正常的 
你可以清除缓存后再进行尝试 如有发现其他问题修复后及优化项可以提交进行合并
